# Generated by Django 5.2.1 on 2025-08-27 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirplaneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('closest_biggest_city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('rows', models.IntegerField()),
                ('seats_in_row', models.IntegerField()),
                ('airplane_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AirportApp.airplanetype')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='AirportApp.airport')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='AirportApp.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(db_index=True)),
                ('arrival_time', models.DateTimeField()),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AirportApp.airplane')),
                ('crew', models.ManyToManyField(blank=True, related_name='flights', to='AirportApp.crew')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AirportApp.route')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('seat', models.IntegerField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AirportApp.flight')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AirportApp.order')),
            ],
        ),
        migrations.AddConstraint(
            model_name='airplane',
            constraint=models.CheckConstraint(condition=models.Q(('rows__gt', 0)), name='rows_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='airplane',
            constraint=models.CheckConstraint(condition=models.Q(('seats_in_row__gt', 0)), name='seats_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.CheckConstraint(condition=models.Q(('source', models.F('destination')), _negated=True), name='prevent_same_airport_route'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.CheckConstraint(condition=models.Q(('distance__gt', 0)), name='distance_gt_zero'),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('source', 'destination')},
        ),
        migrations.AddConstraint(
            model_name='flight',
            constraint=models.CheckConstraint(condition=models.Q(('arrival_time__gt', models.F('departure_time'))), name='arrival_after_departure'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('flight', 'row', 'seat')},
        ),
    ]
